services:
  java_app:
    container_name: java_app
    build:
      context: .  # Ruta al directorio que contiene tu Dockerfile
      dockerfile: dockerfile  # Nombre de tu Dockerfile (opcional si se llama "Dockerfile")
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres